name: health_tracker_unda
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  table_calendar: ^3.0.9
  firebase_auth: ^4.2.5
  firebase_core: ^2.10.0
  cloud_firestore: ^4.15.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logov1.webp